### ISSUE TITLE
Prolific Assistant continuously showing error since site TOS update

### ISSUE THREAD

**Issue by concreteclam** [Kadauchi/prolific-assistant#12] opened 2019-02-12 18:45 UTC
Hey Kadauchi. It seems like the latest Prolific site TOS update broke Prolific Assistant. Before, it would show an error for one "cycle" or two before it understood that I was logged in. Now, it simply shows the error indefinitely. I tried rolling back to an older version, which also didn't work.

**Comment by JoeBoJoe** [comment] 2019-02-12 20:09
I had the same issue as you and I can confirm it was the recent update. I have since rolled back to version 71.0.3578.80 and it is now working again for me. Did you make sure you stopped chrome from automatically updating again?

You can check your current version in Help>About Google Chrome.

I followed 'Method 2' from the following website:
[https://www.makeuseof.com/tag/stop-automatic-chrome-updates-windows/](url)

**Comment by concreteclam** [comment] 2019-02-12 20:18
Where did you get the older release of PA, JoeBoJoe? I have to admit I'm not entirely familiar with using GitHub.

**Comment by JoeBoJoe** [comment] 2019-02-12 20:21
> Hey Kadauchi. It seems like the latest Prolific site TOS update broke Prolific Assistant. Before, it would show an error for one "cycle" or two before it understood that I was logged in. Now, it simply shows the error indefinitely. I tried rolling back to an older version, which also didn't work.

I had the same problem as you but the Firefox version of the extension worked fine so I figured it was a recent Chrome update. Since then I have rolled back my chrome to version 71.0.3578.80 and Prolific Assistant now works again as expected.

I can talk you through how I got an older version of chrome running if you like or you can try giving the Firefox version a go and see if it works for you until Kadauchi can put out a fix.

**Comment by Kadauchi** [comment] 2019-02-12 20:45
Thanks for letting me know. I'll check out what the cause of the issue is.

I would just use Firefox in the interim as @JoeBoJoe suggested.

**Comment by GiacomoLaw** [comment] 2019-02-16 12:32
Yep, facing this issue too.

**Comment by GiacomoLaw** [comment] 2019-02-24 18:29
Seems to be fixed now, thanks!

**Comment by concreteclam** [comment] 2019-02-24 18:37
Working great, thanks Kadauchi!

**Closed** 2019-02-24 19:17 UTC
